routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () { 
    return view('index')
    ->withDriver(App\Models\Driver::all())
    ->withPost(App\Models\Post::orderBy('created_at', 'DESC')->get());
})->name('/');

Route::get('/news/{id}', function ($id) { 
    return view('news')
    ->withPost(App\Models\Post::find($id));
})->name('news');

Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('/register', 'CustomerController@store');

Route::middleware(['auth'])->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::group(['middleware' => ['roles'], 'roles' => ['User', 'Admin']], function () {
        Route::get('/customer/{customer}', 'CustomerController@show')->name('customer.show');
        Route::get('/profile/customer/{customer}/edit', 'CustomerController@edit_profile')->name('customer.edit_profile');
        Route::patch('/update_profile/customer/{customer}', 'CustomerController@update_profile')->name('customer.update_profile');
        // Reservation
        Route::resource('/reservation',  'ReservationController'); 
        // Route::post('/reservation/type', 'ReservationController@type')->name('reservation.type');
        Route::post('/reservation/payment', 'ReservationController@payment')->name('reservation.payment');
        Route::get('/reservation/status/{status}',  'ReservationController@status')->name('reservation.status'); 
        Route::post('/reservation/apporve/{apporve}',  'ReservationController@apporve')->name('reservation.apporve'); 
        Route::get('van/detail/{id}', 'VanController@detail')->name('van.detail');
    });

    Route::group(['middleware' => ['roles'], 'roles' => ['Admin']], function () {
        // User
        Route::resource('/user', 'UserController');
        Route::get('/profile/user/{user}/edit', 'UserController@edit_profile')->name('user.edit_profile');
        Route::patch('/update_profile/user/{user}', 'UserController@update_profile')->name('user.update_profile');
        // Customer
        Route::get('/customer', 'CustomerController@index')->name('customer.index');
        Route::delete('/customer/{customer}', 'CustomerController@destroy')->name('customer.destroy');
        Route::get('/customer/{customer}/edit', 'CustomerController@edit')->name('customer.edit');
        Route::patch('/customer/{customer}', 'CustomerController@update')->name('customer.update');
        // Driver
        Route::resource('/driver', 'DriverController');
        // Van
        Route::resource('van', 'VanController');
        // Post
        Route::resource('post', 'PostController');
    });
});

resources/views/layouts/Backend/breadcrumb.blade.php
<div class="col-md-7 align-self-center font">
    {!! Breadcrumbs::render() !!}
</div>

resources/views/layouts/Backend/footer.blade.php
<footer class="footer" style="font-size:14px"> © {{Carbon::now()->year}} All rights reserved. <a href="{{ route('home') }}">Teerapong Tour</a></footer>

resources/views/layouts/Backend/header.blade.php
        <!-- header header  -->
        <div class="header">
            <nav class="navbar top-navbar navbar-expand-md navbar-light">
                <!-- Logo -->
                <div class="navbar-header">
                    <a class="navbar-brand" href="{{ route('home') }}">
                        <!-- Logo icon -->
                        <b><span class="dark-logo"></span>  TRP </b>
                        <!--End Logo icon -->
                        <span class="dark-logo">Tour</span>
                    </a>
                </div>
                <!-- End Logo -->
                <div class="navbar-collapse">
                    <ul class="navbar-nav mr-auto mt-md-0">
                        <!-- This is  -->
                        <li class="nav-item"> <a class="nav-link nav-toggler hidden-md-up text-muted  " href="javascript:void(0)"><i class="mdi mdi-menu"></i></a> </li>
                        <li class="nav-item m-l-10"> <a class="nav-link sidebartoggler hidden-sm-down text-muted  " href="javascript:void(0)"><i class="ti-menu"></i></a> </li>
                    </ul>
                    <!-- User profile and search -->
                    <ul class="navbar-nav ml-auto mt-md-0">
                        <!-- Profile -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-muted  " href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ Html::image('images/backend/users/'.Auth::user()->image, "User",['class'=>'profile-pic']) }}
                            </a>
                            <div class="dropdown-menu dropdown-menu-right animated zoomIn">
                                <ul class="dropdown-user">
                                    @if(Auth::user()->hasRole('Admin'))
                                    <li><a href="{{ route('user.show', Auth::user()->id) }}"><i class="ti-user"></i> Profile</a></li>
                                    @endif
                                    @if(Auth::user()->hasRole('User'))
                                    <li><a href="{{ route('customer.show', Auth::user()->customer_id) }}"><i class="ti-user"></i> Profile</a></li>
                                    @endif
                                    <li>
                                        <a href="#" onclick="event.preventDefault();document.getElementById('logout-form-header').submit();"><i class="fa fa-power-off"></i> Logout</a>
                                        {!! Form::open(['route' => 'logout', 'id'=>'logout-form-header']) !!} {!! Form::close() !!}
                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
        <!-- End header header -->

resources/views/layouts/Backend/sidebar.blade.php
@php
use Libraries\NotificationLibrary\NotificationLibrary;
@endphp
<!-- Left Sidebar  -->
        <div class="left-sidebar">
            <!-- Sidebar scroll-->
            <div class="scroll-sidebar">
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav">
                    <ul id="sidebarnav">
                        <li class="nav-devider"></li>
                        <li class="nav-label">MENU</li>
                        <li> 
                            <a href="{{ route('home') }}" aria-expanded="false"><i class="fa fa-tachometer"></i><span class="hide-menu"> หน้าหลัก </span></a>
                        </li>
                        @if(Auth::user()->hasRole('Admin'))
                        <li> 
                            <a href="{{ route('customer.index') }}" aria-expanded="false"><i class="fas fa-user-tie"></i><span class="hide-menu"> ข้อมูลลูกค้า </span></a>
                        </li>
                         <li> 
                            <a href="{{ route('driver.index') }}" aria-expanded="false"><i class="far fa-address-card"></i><span class="hide-menu"> ข้อมูลคนขับ </span></a>
                        </li>

                        <li> 
                            <a href="{{ route('van.index') }}" aria-expanded="false"><i class="fas fa-shipping-fast"></i><span class="hide-menu"> ข้อมูลรถตู้ </span></a>
                        </li>
                       
                        <li> 
                            <a href="{{ route('reservation.status', 0) }}" aria-expanded="false"><i class="far fa-calendar-check"></i><span class="hide-menu"> ข้อมูลการจอง </span></a>
                        </li>
                        <li> 
                            <a href="{{ route('reservation.status', 1) }}" aria-expanded="false"><i class="far fa-money-bill-alt"></i><span class="hide-menu"> ข้อมูลแจ้งชำระเงิน </span></a>
                            @if(NotificationLibrary::read())
                            <span class="label label-rouded label-primary pull-right hide-menu" style="margin-top:-31px;margin-right:10px">{{ NotificationLibrary::read() }}</span>
                            @endif
                        </li>
                        <li> 
                            <a href="{{ route('reservation.status', 3) }}" aria-expanded="false"><i class="far fa-times-circle"></i><span class="hide-menu"> ไม่อนุมัติ </span></a>
                        </li>
                         <li> 
                            <a href="{{ route('reservation.status', 2) }}" aria-expanded="false"><i class="fas fa-dollar-sign"></i><span class="hide-menu"> อนุมัติชำระเงิน </span></a>
                        </li>
                        <li> 
                            <a href="{{ route('post.index') }}" aria-expanded="false"><i class="far fa-list-alt"></i><span class="hide-menu"> บทความ </span></a>
                        </li>
                        @else

                        <li> 
                            <a href="{{ route('reservation.create') }}" aria-expanded="false"><i class="fas fa-shipping-fast"></i><span class="hide-menu"> จองรถตู้ </span></a>
                        </li>
                        <li> 
                            <a href="{{ route('reservation.status', 0) }}" aria-expanded="false"><i class="far fa-calendar-check"></i><span class="hide-menu"> ข้อมูลการจอง </span></a>
                        </li>
                        <li> 
                            <a href="{{ route('reservation.status', 1) }}" aria-expanded="false"><i class="far fa-money-bill-alt"></i><span class="hide-menu"> ข้อมูลแจ้งชำระเงิน </span></a>
                        </li>
                         <li> 
                            <a href="{{ route('reservation.status', 3) }}" aria-expanded="false"><i class="far fa-times-circle"></i><span class="hide-menu"> ไม่อนุมัติ </span></a>
                        </li>
                         <li> 
                            <a href="{{ route('reservation.status', 2) }}" aria-expanded="false"><i class="fas fa-dollar-sign"></i><span class="hide-menu"> อนุมัติชำระเงิน </span></a>
                        </li>
                       
                        @endif

                        @if(Auth::user()->hasRole('Admin'))
                        <li class="nav-label">SETTING</li>
                        <li> 
                            <a href="{{ route('user.index') }}" aria-expanded="false"><i class="fa fa-users"></i><span class="hide-menu"> ผู้ใช้งานระบบ </span></a>
                        </li>
                        @endif
                        <li class="nav-label">USER</li>
                        @if(Auth::user()->hasRole('Admin'))
                        <li><a href="{{ route('user.show', Auth::user()->id) }}"><i class="ti-user"></i> Profile</a></li>
                        @endif
                        @if(Auth::user()->hasRole('User'))
                        <li><a href="{{ route('customer.show', Auth::user()->customer_id) }}"><i class="ti-user"></i> Profile</a></li>
                        @endif
                        <li>
                            <a href="#" onclick="event.preventDefault();document.getElementById('logout-form-menu').submit();"><i class="fa fa-power-off"></i> Logout</a>
                            {!! Form::open(['route' => 'logout', 'id'=>'logout-form-menu']) !!} {!! Form::close() !!}
                        </li>
                    </ul>
                </nav>
                <!-- End Sidebar navigation -->
            </div>
            <!-- End Sidebar scroll-->
        </div>
        <!-- End Left Sidebar  -->